from agents import Agent, WebSearchTool, ModelSettings
import sys
from pathlib import Path

# Add parent directory to path for smart_date_manager import
current_dir = Path(__file__).parent
parent_dir = current_dir.parent.parent
sys.path.append(str(parent_dir))

from smart_date_manager import SmartDateManager, create_smart_writing_agent_instructions

# Initialize smart date manager
smart_date_manager = SmartDateManager()

import os
import sendgrid
from sendgrid.helpers.mail import Email, Mail, Content, To

@Agent.function_tool
def send_job_search_email(report_content: str) -> dict:
    """Send the job search report via email to Jack Agnew"""
    try:
        sg = sendgrid.SendGridAPIClient(api_key=os.environ.get('SENDGRID_API_KEY'))
        from_email = Email("jack@clevelsalesguy.com")
        to_email = To("jack@clevelsalesguy.com")
        subject = "Job Search Report - AI/Technology Enterprise Sales Opportunities"
        
        # Create HTML content
        html_content = f"""
        <html>
        <body>
        <h2>🎯 Job Search Report - AI/Technology Enterprise Sales</h2>
        <p><strong>Generated:</strong> {os.popen('date').read().strip()}</p>
        <div style="white-space: pre-wrap; font-family: Arial, sans-serif;">
        {report_content}
        </div>
        <hr>
        <p><em>This report was generated by your AI Job Search Assistant.</em></p>
        </body>
        </html>
        """
        
        content = Content("text/html", html_content)
        mail = Mail(from_email, to_email, subject, content)
        
        response = sg.client.mail.send.post(request_body=mail.get())
        return {"status": "success", "status_code": response.status_code}
    except Exception as e:
        return {"status": "error", "message": str(e)}

INSTRUCTIONS = INSTRUCTIONS = """You are an email assistant that sends job search reports. 
You will be provided with a comprehensive job search report and should send it via email 
to Jack Agnew at jack@clevelsalesguy.com with an appropriate subject line and formatting."""

job_email_agent = Agent(
    name="JobEmailAgent",
    instructions=INSTRUCTIONS,
    tools=[send_job_search_email],
    model="gpt-4o-mini",

        
DATE AWARENESS INSTRUCTIONS:
- Current Date: September 24, 2025
- Current Year: 2025

IMPORTANT: Use dates intelligently based on context:
- For NEW content (cover letters, reports, emails): Use current date (September 24, 2025)
- For HISTORICAL content: Preserve existing dates, don't change them
- For DRAFTS of previously sent documents: Use the original date, not current date
- For UPDATES to existing documents: Use current date for new sections, preserve original dates for existing sections

Context: email
- If creating new email: Use current date
- If updating existing email: Preserve historical dates, use current date only for new content
- If referencing historical events: Use appropriate historical dates

DO NOT overwrite dates that are historically correct or contextually appropriate.

