#!/usr/bin/env python3
"""
Document Template with Date Management
Template for creating AI-generated documents with accurate timestamps
"""

import os
from datetime import datetime
from date_manager import get_formatted_date, get_current_datetime

class DocumentTemplate:
    """Base template for AI-generated documents with proper date handling"""
    
    def __init__(self, title, document_type="AI Generated Document"):
        self.title = title
        self.document_type = document_type
        self.created_date = get_formatted_date('standard')
        self.created_datetime = get_current_datetime()
        self.last_updated = get_formatted_date('standard')
    
    def get_header(self):
        """Get standardized document header"""
        return f"""
# {self.title}

**Document Type:** {self.document_type}  
**Created:** {self.created_date}  
**Last Updated:** {self.last_updated}  
**Generated By:** AI Assistant  

---

"""
    
    def get_footer(self):
        """Get standardized document footer"""
        return f"""

---

*This document was generated by an AI assistant on {self.created_date}.  
For questions or updates, please refer to the source data or regenerate the document.*
"""
    
    def update_timestamp(self):
        """Update the last updated timestamp"""
        self.last_updated = get_formatted_date('standard')
    
    def get_metadata(self):
        """Get document metadata as dictionary"""
        return {
            'title': self.title,
            'document_type': self.document_type,
            'created_date': self.created_date,
            'created_datetime': self.created_datetime,
            'last_updated': self.last_updated,
            'generated_by': 'AI Assistant'
        }

def create_document_with_dates(title, content, document_type="AI Generated Document"):
    """Create a document with proper date handling"""
    template = DocumentTemplate(title, document_type)
    
    full_content = template.get_header() + content + template.get_footer()
    
    return {
        'content': full_content,
        'metadata': template.get_metadata()
    }

# Example usage
if __name__ == "__main__":
    print("📄 Document Template Test")
    print("=" * 50)
    
    # Test document creation
    sample_content = """
## Introduction
This is a sample document to demonstrate proper date handling.

## Key Points
- Always use current date
- Include creation timestamp
- Track last updated
- Provide metadata

## Conclusion
This ensures consistency across all AI-generated documents.
"""
    
    doc = create_document_with_dates(
        "Sample Document", 
        sample_content, 
        "Test Document"
    )
    
    print("Document Content:")
    print(doc['content'])
    
    print("\nDocument Metadata:")
    for key, value in doc['metadata'].items():
        print(f"  {key}: {value}")
