"""Setup script for job-search-assistant."""

from setuptools import setup, find_packages

setup(
    name="job-search-assistant",
    version="1.0.0",
    description="AI-powered job search assistant for enterprise sales positions",
    author="Jack Agnew",
    author_email="jack@clevelsalesguy.com",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.11",
    install_requires=[
        "fastapi>=0.104.0",
        "uvicorn>=0.24.0",
        "sqlalchemy>=2.0.0",
        "pydantic>=2.0.0",
        "python-dotenv>=1.0.0",
        "sendgrid>=6.0.0",
        "alembic>=1.12.0",
        "psycopg2-binary>=2.9.0",
        "redis>=5.0.0",
        "celery>=5.3.0",
        "beautifulsoup4>=4.12.0",
        "lxml>=4.9.0",
        "pypdf>=3.17.0",
        "python-docx>=1.1.0",
        "reportlab>=4.0.0",
        "jinja2>=3.1.0",
        "httpx>=0.25.0",
        "aiofiles>=23.2.0",
        "python-multipart>=0.0.6",
        "python-jose>=3.3.0",
        "passlib>=1.7.4",
        "bcrypt>=4.1.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.0",
            "pytest-asyncio>=0.21.0",
            "pytest-cov>=4.1.0",
            "pytest-mock>=3.12.0",
            "black>=23.11.0",
            "isort>=5.12.0",
            "mypy>=1.7.0",
            "flake8>=6.1.0",
            "bandit>=1.7.0",
            "safety>=2.3.0",
            "semgrep>=1.45.0",
            "pre-commit>=3.5.0",
            "playwright>=1.40.0",
            "coverage>=7.3.0",
            "pytest-html>=4.1.0",
            "pytest-xdist>=3.5.0",
        ],
    },
)