#!/usr/bin/env bash

# Software Factory Observability Setup Script
# This script helps set up observability for any project created by the factory

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

function log() {
  echo "[factory-observability] $*"
}

function check_dependencies() {
  log "Checking dependencies..."
  
  # Check if Node.js is available
  if ! command -v node &> /dev/null; then
    log "❌ Node.js is required but not installed"
    exit 1
  fi
  
  # Check if npm/yarn is available
  if ! command -v npm &> /dev/null && ! command -v yarn &> /dev/null; then
    log "❌ npm or yarn is required but not installed"
    exit 1
  fi
  
  log "✅ Dependencies check passed"
}

function setup_env_file() {
  log "Setting up environment file..."
  
  local env_file="$PROJECT_ROOT/.env"
  
  if [[ -f "$env_file" ]]; then
    log "📄 .env file already exists"
    if grep -q "FACTORY_" "$env_file"; then
      log "✅ Factory variables already present in .env"
      return
    fi
  else
    log "📄 Creating .env file"
    touch "$env_file"
  fi
  
  log "Please add the following variables to your .env file:"
  echo ""
  echo "# Factory Observability"
  echo "FACTORY_SUPABASE_URL=https://your-project.supabase.co"
  echo "FACTORY_SUPABASE_SERVICE_KEY=your-service-role-key"
  echo "# OR use anon key for client-side apps"
  echo "FACTORY_SUPABASE_ANON_KEY=your-anon-key"
  echo ""
  
  read -p "Press Enter when you've added the variables to .env..."
}

function copy_observability_files() {
  log "Copying observability files..."
  
  local target_dir="$PROJECT_ROOT/factory"
  
  if [[ ! -d "$target_dir" ]]; then
    mkdir -p "$target_dir"
  fi
  
  # Copy observability files
  cp "$SCRIPT_DIR/observability.ts" "$target_dir/"
  cp "$SCRIPT_DIR/observability.js" "$target_dir/"
  cp "$SCRIPT_DIR/supabase-observability.sql" "$target_dir/"
  
  log "✅ Observability files copied to $target_dir"
}

function setup_observability_helpers() {
  log "Setting up observability helpers..."
  
  local target_dir="$PROJECT_ROOT/src/lib"
  
  if [[ ! -d "$target_dir" ]]; then
    mkdir -p "$target_dir"
  fi
  
  # Create observability service if it doesn't exist
  if [[ ! -f "$target_dir/observability.ts" ]]; then
    cat > "$target_dir/observability.ts" << 'EOF'
/**
 * Project Observability Integration
 * Auto-generated by Software Factory
 */

import { 
  trackAIAnalysis, 
  trackAIError, 
  trackTestRun, 
  trackGenericEvent 
} from '../../factory/observability';

const APP_NAME = 'your-app-name'; // Update this with your app name

export class ProjectObservability {
  static async trackAIAnalysis(
    service: string,
    status: 'success' | 'failure',
    fallbackUsed: boolean,
    processingTimeMs: number,
    metadata?: Record<string, unknown>
  ) {
    if (status === 'success') {
      await trackAIAnalysis({
        app: APP_NAME,
        service,
        status,
        fallbackUsed,
        processingTimeMs,
        metadata
      });
    } else {
      await trackAIError({
        app: APP_NAME,
        service,
        status,
        fallbackUsed,
        processingTimeMs,
        metadata
      });
    }
  }

  static async trackUserEvent(
    eventName: string,
    payload?: Record<string, unknown>
  ) {
    await trackGenericEvent({
      app: APP_NAME,
      name: eventName,
      payload: {
        timestamp: new Date().toISOString(),
        ...payload
      }
    });
  }

  static async trackTestExecution(
    pipeline: string,
    status: 'pass' | 'fail',
    details?: string
  ) {
    await trackTestRun({
      app: APP_NAME,
      pipeline,
      status,
      details
    });
  }
}
EOF
    log "✅ Created observability service template at src/lib/observability.ts"
  else
    log "✅ Observability service already exists"
  fi
}

function test_observability() {
  log "Testing observability setup..."
  
  # Load environment variables
  source "$PROJECT_ROOT/scripts/load-factory-env.sh"
  
  # Test if variables are loaded
  if [[ -n "${FACTORY_SUPABASE_URL:-}" ]]; then
    log "✅ Environment variables loaded successfully"
  else
    log "⚠️  Environment variables not loaded. Run: source scripts/load-factory-env.sh"
  fi
}

function show_next_steps() {
  log "🎉 Observability setup complete!"
  echo ""
  echo "Next steps:"
  echo "1. Update APP_NAME in src/lib/observability.ts"
  echo "2. Run the Supabase SQL schema: factory/supabase-observability.sql"
  echo "3. Load environment variables: source scripts/load-factory-env.sh"
  echo "4. Start tracking events in your app!"
  echo ""
  echo "For detailed usage, see: factory/OBSERVABILITY_GUIDE.md"
}

function main() {
  log "🚀 Setting up Software Factory Observability"
  echo ""
  
  check_dependencies
  setup_env_file
  copy_observability_files
  setup_observability_helpers
  test_observability
  show_next_steps
}

main "$@"
